export type Service = {
  slug: string;
  name: string;
  description: string;
  highlights?: string[];
  dimensions: string;
  duration: string;
  price: string;
  images: string[];
  category: string[];
  featured?: boolean;
  includesOperator: boolean;
};

export const services: Service[] = [
  {
    slug: "alquiler-toro-mecanico-cordoba",
    name: "Toro Mecánico",
    description: "¡El alma de la fiesta! Nuestro Toro Mecánico ofrece una experiencia de rodeo auténtica y segura en toda la provincia de Córdoba. Con niveles de intensidad regulables, es la atracción ideal tanto para niños como para adultos valientes. Cuenta con un colchón inflable de alta resistencia para amortiguar cada caída, garantizando carcajadas y adrenalina en un entorno controlado por expertos.",
    highlights: [
      "Apto para todas las edades",
      "Control de velocidad variable",
      "Colchón inflable perimetral de máxima seguridad",
      "Servicio con operador especializado durante todo el evento",
      "Cobertura en toda la Provincia de Córdoba",
      "Ideal para fiestas de 15, cumpleaños y eventos corporativos",
      "Se instala en espacios abiertos o cerrados",
    ],
    dimensions: "5m x 5m aprox.",
    duration: "3 horas",
    price: "150.000",
    images: [
      "/juegos/toro.jpg",
      "/juegos/toro-2.jpg",
      "/juegos/toro-3.jpg",
      "/juegos/toro-4.jpg",
      "/juegos/toro-5.jpg",
      "/juegos/toro-6.jpg",
      "/juegos/toro-7.jpg",
    ],
    category: [
      "Juegos de parque",
      "Juegos de cumple",
      "Juegos al aire libre",
      "Juegos de interior",
      "Casamiento",
      "15s",
      "Despedidas",
      "Juegos de adultos",
      "Juegos infantiles",
    ],
    featured: true,
    includesOperator: true,
  },
  {
    slug: "alquiler-reloj-loco-cordoba",
    name: "Reloj Loco",
    description: "¡El desafío definitivo para tu evento! El Reloj Loco es el juego inflable mecánico líder en Córdoba para quienes buscan adrenalina y risas. Este inflable giratorio pone a prueba los reflejos: debés saltar o agacharte para esquivar el brazo mecánico sin caer del colchón.",
    highlights: [
      "Diversión garantizada para niños, adolescentes y adultos",
      "Incluye traslado y operador especializado",
      "Apto para interior o exterior",
      "Materiales de alta resistencia",
    ],
    dimensions: "7m de diámetro",
    duration: "Hasta 5 horas",
    price: "Consultar por WhatsApp",
    images: [
      "/juegos/reloj.jpg",
      "/juegos/reloj-2.jpg",
      "/juegos/reloj-4.jpg"
    ],
    category: [
      "Juegos de parque",
      "Juegos de cumple",
      "Juegos al aire libre",
      "Juegos de interior",
      "Casamiento",
      "15s",
      "Despedidas",
      "Juegos de adultos", 
      "Juegos infantiles",
    ],
    featured: true,
    includesOperator: true,
  },
  {
    slug: "alquiler-maquina-boxeo-arcade-cordoba",
    name: "Máquina Arcade de Boxeo con Patada",
    description: "¿Quién tiene el golpe más fuerte? Llevá la adrenalina de los salones arcade a tu evento en Córdoba con nuestra Máquina de Boxeo y Patada 2 en 1. Medi la potencia de tu puño y patada en tiempo real.",
    highlights: [
      "Doble desafío: Puño y patada",
      "Display digital con récord histórico",
      "Compacta y estética: Se adapta a cualquier salón",
      "Ideal para Eventos Masivos, Bares y Cumples de 18",
    ],
    dimensions: "2m x 1m aprox.",
    duration: "Jornada completa",
    price: "Consultar por WhatsApp",
    images: [
      "/juegos/boxeo.jpg",
      "/juegos/boxeo-2.jpg",
      "/juegos/boxeo-3.jpg",
      "/juegos/boxeo-4.jpg",
    ],
    category: [
      "Kermes",
      "Arcade",
      "Juegos al aire libre",
      "Juegos de interior",
      "Casamiento",
      "15s",
      "Despedidas",
      "Juegos de adultos",
    ],
    featured: true,
    includesOperator: false,
  },
  {
    slug: "alquiler-maquina-espuma-cordoba",
    name: "Volcan de Espuma Profesional",
    description: "¡Llevá tu fiesta al siguiente nivel con una explosión de espuma! Nuestro cañón de alta potencia es el alma de las Pool Parties en Córdoba. Insumos hipoalergénicos de primera calidad.",
    highlights: [
      "Espuma premium: Atóxica e hipoalergénica",
      "No mancha la ropa",
      "Efecto visual de alto impacto",
      "Servicio con operador incluido",
    ],
    dimensions: "Espacio abierto",
    duration: "A convenir",
    price: "Consultar por WhatsApp",
    images: [
      "/juegos/espuma-3.jpg",
      "/juegos/espuma-2.jpg",
      "/juegos/espuma-4.jpg",
      "/juegos/espuma.jpg",
      "/juegos/espuma-5.jpg",
      "/juegos/espuma-6.jpg",
      "/juegos/espuma-7.jpg",
      "/juegos/espuma-8.jpg",
      "/juegos/espuma-9.jpg",
      "/juegos/espuma-10.jpeg",
    ],
    category: [
      "Juegos al aire libre",
      "Acuatico",
      "Juegos de cumple",
      "Juegos de parque",
      "Juegos de adultos", 
      "Juegos infantiles",
      "Despedidas",
    ],
    featured: true,
    includesOperator: false,
  },
  {
    slug: "alquiler-castillo-inflable-palmera-cordoba",
    name: "Castillo Palmera con Tobogán",
    description: "¡Un oasis de diversión! Combina zona de saltos tipo pelotero con un tobogán súper ancho donde pueden deslizarse hasta tres niños en simultáneo.",
    highlights: [
      "Tobogán Triple: ¡Tres niños a la vez!",
      "Función 3 en 1: Salto, pelotero y tobogán",
      "Diseño Tropical vibrante",
    ],
    dimensions: "6m x 4m aprox.",
    duration: "Jornada completa",
    price: "Consultar por WhatsApp",
    images: [
      "/juegos/palmera.jpg",
      "/juegos/palmera-2.jpg",
      "/juegos/palmera-3.jpg",
    ],
    category: [
      "Juegos de cumple",
      "Juegos de interior",
      "Juegos al aire libre",
      "inflable tematico",
      "Juegos infantiles",
    ],
    featured: true,
    includesOperator: false,
  },
  { 
    slug: "castillo-3x3", 
    name: "Castillo 3x3", 
    description: "El clásico inflable que se adapta a cualquier jardín. Ideal para los más chiquitos.",
    dimensions: "3m x 3m",
    duration: "Jornada completa",
    price: "Consultar por WhatsApp",
    images: ["/juegos/3x3.jpg"],
    category: [
      "Inflable clasico",
      "Juegos de cumple",
      "Juegos al aire libre",
      "Juegos de interior",
      "Juegos infantiles",
    ],
    includesOperator: false,
  },
  {
    slug: "alquiler-jumping-5-camas-cordoba",
    name: "Jumping 5 camas",
    description: "La atracción de alto impacto que redefine cualquier evento masivo. Nuestro Jumping de 5 camas elásticas permite a los participantes realizar saltos y acrobacias a gran altura con total seguridad. Gracias a su sistema de arneses profesionales y asistencia personalizada, es el centro de atención visual ideal para grandes predios, festivales y eventos masivos Córdoba, garantizando una alta rotación de público y adrenalina pura.",
    highlights: [
      "Capacidad: 5 saltadores simultáneos",
      "Arneses profesionales",
      "Constante supervisión",
      "Estructura imponente de gran visibilidad a distancia",
    ],
    dimensions: "6m de diámetro",
    duration: "Consultar",
    price: "Consultar por WhatsApp",
    images: [
      "/juegos/jumping-5-3.jpg",
      "/juegos/jumping-5.jpg",
      "/juegos/jumping-5-1.jpg",
      "/juegos/jumpings.jpg"
    ],
    category: [
      "Juegos de parque",
      "Juegos de exterior",
      "Juegos infantiles",
    ],
    featured: true,
    includesOperator: true,
  },
  {
    slug: "alquiler-super-jumping-7-camas-cordoba",
    name: "Jumping 7 camas",
    description: "El jumping más grande de Córdoba. La atracción definitiva, diseñado para maximizar el flujo de participantes en eventos de alta concurrencia. Este equipo ofrece una visibilidad inigualable desde cualquier punto del predio. Combina adrenalina extrema con un sistema de seguridad de triple redundancia, permitiendo acrobacias aéreas de alto impacto bajo supervisión experta",
    highlights: [
      "Capacidad 7 personas simultaneo",
      "Ideal para festivales masivos",
      "Estructura de alto rendimiento",
      "Estructura imponente de gran visibilidad a distancia",
    ],
    dimensions: "8m de diámetro",
    duration: "Consultar",
    price: "Consultar por WhatsApp",
    images: [
      "/juegos/jumping-7.jpg",
      "/juegos/jumping-7-1.jpg",
      "/juegos/jumpings.jpg",
    ],
    category: [
      "Juegos de parque",
      "Juegos de exterior",
      "Juegos infantiles",
    ],
    includesOperator: true,
  },
  {
    slug: "alquiler-caminata-lunar-minion-gigante-cordoba",
    name: "Caminata Lunar Minion Gigante",
    description: "Un gigante amarillo de 8 metros de altura. Ofrece una experiencia de salto XXL única en el mercado.",
    highlights: [
      "Altura imponente: 8 metros",
      "Formato Caminata Lunar",
      "Personaje favorito de los niños",
    ],
    dimensions: "9m diámetro x 8m alto",
    duration: "Jornada completa",
    price: "Consultar por WhatsApp",
    images: [
      "/juegos/miniom.jpg",
      "/juegos/miniom-2.jpg",
      "/juegos/miniom-3.jpg",
      "/juegos/miniom-4.jpg",
    ],
    category: [
      "Juegos de parque",
      "Juegos de exterior",
      "Inflable tematico",
      "Juegos infantiles",
    ],
    includesOperator: false,
  },
  {
    slug: "alquiler-calesita-infantil-cordoba",
    name: "Calesita",
    description: "Capacidad para 5 niños con personajes animados como el clasico Pluto. Velocidad controlada y segura.",
    dimensions: "3m de diámetro",
    duration: "Jornada completa",
    price: "Consultar por WhatsApp",
    images: [
      "/juegos/calecita.jpeg",
      "/juegos/calecita-1.jpeg",
    ],
    category: [
      "Juegos de parque",
      "Juegos de exterior",
      "Juegos infantiles",
    ],
    includesOperator: false,
  },
  {
    slug: "alquiler-trencito-paseo-infantil-cordoba",
    name: "Trencito de Paseo Motorizado",
    description: "Locomotora profesional y vagón para 6 niños. Conducido por un operador experto.",
    dimensions: "Consultar según recorrido",
    duration: "Consultar",
    price: "Consultar por WhatsApp",
    images: [
      "/juegos/trencito.jpeg",
      "/juegos/trencito-1.jpeg",
    ],
    category: [
      "Juegos de parque",
      "Juegos de exterior",
      "Juegos infantiles",
    ],
    includesOperator: true,
  },
  {
    slug: "alquiler-tobogan-acuatico-premium-cordoba",
    name: "Tobogán Acuático con Túneles y Doble Caída",
    description: "Doble caída y zona previa de obstáculos con túneles circulares. El rey de las Pool Parties.",
    dimensions: "7m x 4m aprox.",
    duration: "Jornada completa",
    price: "Consultar por WhatsApp",
    images: [
      "/juegos/acuatico-con-obstaculos.jpeg",
      "/juegos/acuatico-con-obstaculos-2.jpeg",
      "/juegos/acuatico-con-obstaculos-3.jpeg",
    ],
    category: [
      "Acuatico",
      "Juegos de exterior",
      "Juegos de adultos",
      "Juegos infantiles",
    ],
    includesOperator: false,
  },
  {
    slug: "alquiler-castillo-inflable-jungla-cordoba",
    name: "Castillo Inflable La Jungla",
    description: "Nuestro juego insignia. Diseño vibrante lleno de animales, seguro y espacioso.",
    dimensions: "5m x 4m",
    duration: "Jornada completa",
    price: "Consultar por WhatsApp",
    images: ["/juegos/castillo-jungla.jpeg"],
    category: [
      "Juegos de cumple",
      "Juegos al aire libre",
      "Inflable tematico",
      "Juegos infantiles",
    ],
    includesOperator: false,
  },
  {
    slug: "cocodrilo",
    name: "Cocodrilo",
    description: "¡Una aventura salvaje en tu evento! Nuestro Inflable Gigante Cocodrilo es la combinación perfecta de impacto visual y diversión extrema. Con una imponente boca de cocodrilo al frente, este tobogán de 6 metros permite que hasta 5 niños se deslicen en simultáneo, garantizando un flujo constante de juego y adrenalina. Fabricado con lona de alta densidad y costuras reforzadas, ofrece una experiencia segura y emocionante para los pequeños exploradores.",
    highlights: [
      "Tobogán de gran altura con descenso múltiple",
      "Imponente y llamativo",
      "Paredes laterales altas y firmes para máxima seguridad",
    ],
    dimensions: "6m x 3m",
    duration: "3 horas",
    price: "350.000",
    images: [
      "/juegos/Cocodrilo.jpeg",
      "/juegos/cocodrilo-1.jpeg",
      "/juegos/cocodrilo-2.jpeg",
      "/juegos/cocodrilo-3.jpeg",
      "/juegos/cocodrilo-4.jpeg",
    ],
    category: [
      "Juegos de parque",
      "Juegos al aire libre",
      "Inflable tematico",
      "Juegos infantiles",
    ],
    includesOperator: false,
  },
  {
    slug: "alquiler-palestra-escalada-gigante-cordoba",
    name: "Palestra de Escalada Profesional",
    description: "El desafío definitivo para los más aventureros. Nuestra Palestra Inflable Gigante combina la emoción de la escalada con la adrenalina de un tobogán de alto impacto. Con 6 metros de altura, ofrece dos vías de ascenso: una pared posterior con redes de asistencia y una rampa frontal con soga de fuerza. Una vez en la cima, el descenso se realiza por un imponente tobogán con capacidad para 4 niños en simultáneo, asegurando diversión constante y una base inflable perimetral que garantiza aterrizajes suaves y seguros.",
    highlights: [
      "Doble desafío: Escalada técnica y tobogán de alta velocidad",
      "Dos vías de ascenso, redes reforzadas y soga de seguridad",
      "Gran capacidad, 4 descensos en simultáneo",
      "Base inflable de seguridad para amortiguación total",
      "Estructura imponente de 6 metros de altura con gran visibilidad",
    ],
    dimensions: "Base: 11m x 6m Alto: 6m",
    duration: "3 horas",
    price: "250.000",
    images: [
      "/juegos/palestra.jpeg",
      "/juegos/palestra-1.jpeg",
      "/juegos/palestra-2.jpeg",
      "/juegos/palestra-3.jpeg",
    ],
    category: [
      "Juegos de parque",
      "Juegos de cumple",
      "Juegos al aire libre",
      "Juegos infantiles",
    ],
    includesOperator: true,
  },
  {
    slug: "alquiler-cancha-futbol-inflable-cordoba",
    name: "Cancha de Fútbol Inflable",
    description: "¿Que se obtiene al mezclar tu deporte favorito con saltos descomunales?¡El partido de tu vida! Nuestra cancha inflable lleva el fútbol a otra dimensión, donde cada pase es una acrobacia y cada gol se festeja rebotando por los aires. Es la combinación perfecta entre la pasión de la redonda y la libertad de saltar sin parar. Lo mejor de todo es que pueden darlo todo en cada jugada con total tranquilidad, ya que su estructura amortiguada y paredes de contención están diseñadas para que la única preocupación sea quién mete el próximo gol.",
    highlights: [
      "Diversión potenciada, explora el joga bonito",
      "Fútbol sin límites, sentite un futbolista de elite haciendo acrobacias sin riesgos",
      "Aca nacen los cracks. Goles de palomita y chilena sin riesgo",
      "Seguridad total: Base y laterales inflables que protegen de golpes y caídas",
    ],
    dimensions: "8m x 5m",
    duration: "3 horas",
    price: "120.000",
    images: [
      "/juegos/cancha-inflable-3.jpg",
      "/juegos/cancha-inflable-1.jpg",
      "/juegos/cancha-inflable.jpg",
    ],
    category: [
      "Juegos de cumple",
      "Juegos al aire libre",
      "Inflable tematico",
      "Juegos infantiles",
      "Juegos de adultos",
    ],
    includesOperator: false,
  },
  {
    slug: "alquiler-metegol-humano-cordoba",
    name: "Metegol Humano",
    description: "Capacidad para 10 a 12 jugadores. Ideal para Team Building y eventos escolares.",
    dimensions: "12m x 6m",
    duration: "3 horas",
    price: "130.000",
    images: [
      "/juegos/metegol-inflable-1.jpg",
      "/juegos/metegol-inflable-2.jpg",
      "/juegos/cancha-lona.jpeg",
      "/juegos/cancha-lona-1.jpeg",
      "/juegos/metegol-inflable.jpg",
    ],
    category: [
      "Juegos de cumple",
      "Juegos al aire libre",
      "Acuatico",
      "Juegos infantiles",
      "Juegos de adultos",
    ],
    includesOperator: false,
  },
  {
    slug: "alquiler-ring-boxeo-inflable-cordoba",
    name: "Ring de Boxeo Inflable",
    description: "¿Qué obtenés al mezclar el boxeo de campeonato con el rebote infinito de un inflable? ¡El combate más divertido de tu vida! Subite al cuadrilátero para vivir una pelea épica donde las caídas terminan en risas. Con nuestros guantes gigantes cada golpe es un almohadonazo de pura diversion y cada round es una fiesta. Es la oportunidad perfecta para desafiar a tus amigos en un entorno de pura adrenalina, donde el único nocaut posible es el dolor de panza por la risa.",
    highlights: [
      "Incluye 2 pares de guantes gigantes",
      "Diversión extrema: ¡Peleas de campeonato con rebotes constantes!",
      "Ideal para adolescentes, adultos y niños valientes",
      "¡Show garantizado para los espectadores!",
      "Base de alto impacto para aterrizajes suaves",
      "Cuerdas y esquinas de lona inflable para evitar accidentes.",
      "Base sobre saliente para evitar caidas",
    ],
    dimensions: "5.5m x 5.5m (Espacio libre)",
    duration: "3 horas",
    price: "150.000",
    images: [
      "/juegos/ring-1.jpeg",
      "/juegos/ring.jpeg",
      "/juegos/ring-2.jpeg",

    ],
    category: [
      "Juegos de cumple",
      "Juegos al aire libre",
      "Inflable tematico",
      "Juegos de adultos",
    ],
    includesOperator: false,
  },
  {
    slug: "carrera-obstaculos",
    name: "Carrera de obstaculos",
    description: "¿Qué obtenés al mezclar una pista de entrenamiento ninja con la locura de un mundo inflable? ¡La carrera más frenética de tu vida! Sumergite en un laberinto de 8 metros donde el objetivo es simple: llegar a la otra punta esquivando, saltando o llevándote puesto todo lo que encontrás a tu paso. Es como navegar en una jungla de aire donde cada obstáculo es un desafío y cada rebote te acerca a la meta. Un recorrido épico diseñado para quienes aman la adrenalina y no tienen miedo de lanzarse de cabeza a la diversión.",
    highlights: [
      "Circuito de 8 metros con múltiples desafíos internos",
      "Bosque de cilindros, muros y túneles inflables",
      "Ideal para competencias ¿Quién llega primero?",
      "Alta capacidad de rotación: ¡Entran por un lado y salen por el otro!",
      "Seguridad garantizada: Paredes de contención y base ultra-acolchada",
      "Lona de alta densidad preparada para el uso más intenso",
    ],
    dimensions: "8m x 3m",
    duration: "3 horas",
    price: "100.000",
    images: [
      "/juegos/carrera-de-obstaculos.jpeg",
      "/juegos/carrera-de-obstaculos-1.jpeg",
      "/juegos/carrera-de-obstaculos-3.jpeg",
      "/juegos/carrera-de-obstaculos-2.jpeg",
      "/juegos/carrera-de-obstaculos-4.jpeg",

    ],
    category: [
      "Juegos de cumple",
      "Juegos al aire libre",
      "Juegos infantiles",
      "Juegos de adultos",
    ],
    includesOperator: false,
  },
  {
    slug: "arco-de-futbol-inflable",
    name: "Arco inflable de futbol",
    description: "¿Qué obtenés al mezclar la emoción de un penal decisivo con el rebote extremo de un estadio inflable? ¡El gol más espectacular de tu vida! Nuestro Mega Arco transforma cualquier jardín en una final de campeonato, donde cada remate se vive con la intensidad de un profesional. Con 4 metros de ancho y una red de contención reforzada, es el escenario perfecto para desafiar a tus amigos, practicar puntería o simplemente volar de palo a palo sintiendo la seguridad de un aterrizaje suave y divertido.",
    highlights: [
      "Red de contención trasera de alta resistencia",
      "Ideal para competencias de penales y tiros libres",
      "Estructura 100% inflable",
      "Instalación flash: ¡Listo para jugar en menos de 5 minutos!",
    ],
    dimensions: "4m x 3m",
    duration: "3 horas",
    price: "80.000",
    images: [
      "/juegos/arco-de-futbol.jpeg",
      "/juegos/arco-de-futbol-2.jpeg",
    ],
    category: [
      "Juegos de parque",
      "Juegos de cumple",
      "Kermes",
      "Juegos al aire libre",
      "Inflable tematico",
      "Juegos infantiles",
      "Juegos de adultos",
    ],
    includesOperator: false,
  },
  {
    slug: "metegol",
    name: "Metegol",
    description: "¿Qué obtenés al mezclar la pasión de un estadio lleno con la velocidad de tus propios reflejos? ¡El partido más intenso de tu vida! Nuestro metegol profesional de fundición de aluminio está diseñado para los que no juegan solo por diversión, sino por la gloria. Sentí la adrenalina de cada pase filtrado y el estruendo de un gol de campeonato en una mesa ultra resistente que aguanta hasta los partidos más picantes. Es el corazón de cualquier previa, cumple o evento corporativo donde la competencia y las risas nunca se detienen.",
    highlights: [
      "Estructura de fundición de aluminio de alta resistencia",
      "Barras de acero reforzado para un juego rápido y preciso",
      "Ideal para torneos relámpago en eventos y oficinas",
      "¡No se mueve ni en los goles más gritados!",
    ],
    dimensions: "1.5m x 1m",
    duration: "Jornada completa",
    price: "50.000",
    images: [
      "/juegos/metegol-1.jpeg",
      "/juegos/metegol.jpeg",
      "/juegos/metegol-3.jpeg",
    ],
    category: [
      "Juegos de estar",
      "Juegos de cumple",
      "Juegos de interior",
      "Juegos al aire libre",
      "Juegos infantiles",
      "Juegos de adultos",
    ],
    includesOperator: false,
  },
  {
    slug: "videojuego",
    name: "Videojuego",
    description: "Arcade clásico multijuego.",
    dimensions: "0.8m x 0.6m",
    duration: "Jornada completa",
    price: "50.000",
    images: ["/juegos/videojuego.jpg"],
    category: [
      "Juegos de estar",
      "Juegos de cumple",
      "Juegos de interior",
      "Juegos al aire libre",
      "Juegos infantiles",
      "Juegos de adultos",
      "Arcade",
    ],
    includesOperator: false,
  },
  {
    slug: "penta-penal",
    name: "Penta penal",
    description: "",
    dimensions: "",
    duration: "Jornada completa",
    price: "80.000",
    images: [
      "/juegos/pentapenal.jpg",
      "/juegos/pentapenal-2.jpg",
    ],
    category:[
      "Kermes",
      "Juegos de cumple",
      "Juegos al aire libre",
      "Juegos infantiles",
      "Juegos de adultos",
    ],
    includesOperator: false,
  },
  {
    slug: "vuelta-al-mundo",
    name: "Vuelta al mundo",
    description: "Atracción mecánica clásica de feria para niños.",
    dimensions: "4m de diámetro",
    duration: "Jornada completa",
    price: "1.000.000",
    images: ["/juegos/vuelta-al-mundo.jpeg"],
    category: [
      "Juego de parque",
      "Corporativo",
      "Juegos al aire libre",
      "Juegos infantiles",
      "15s",
    ],
    includesOperator: true,
  },
  {
    slug: "aviones-voladeres",
    name: "Aviones voladores",
    description: "Juego mecánico de aviones giratorios.",
    dimensions: "5m de diámetro",
    duration: "3 horas",
    price: "350.000",
    images: [
      "/juegos/voladores.jpeg",
      "/juegos/voladores-1.jpeg",
      "/juegos/voladores-2.jpeg",
    ],
    category: [
      "Juegos de parque",
      "Juegos al aire libre",
      "Juegos infantiles",
      "Corporativo",
    ],
    includesOperator: true,
  },
  /*
  {
    slug: "alquiler-tobogan-acuatico-cordoba",
    name: "Tobogán Acuático Clasico",
    description: "Subida rápida para maximizar los saltos. Ideal para Pool Parties residenciales.",
    dimensions: "5m x 3m",
    duration: "3 horas",
    price: "100.000",
    images: ["/juegos/acuatico.jpg"],
    category: [
      "Juegos de cumple",
      "Acutatico",
      "Juegos al aire libre",
      "Juegos infantiles",
      "Juegos de adultos",
    ],
    includesOperator: false,
  },
  {
    slug: "mini-bus",
    name: "Mini bus",
    description: "Juego estático para niños pequeños con temática de transporte.",
    dimensions: "2m x 1m",
    duration: "Jornada completa",
    price: "1.000.000",
    images: ["/juegos/mini-bus.jpg"],
    category: [
      "Juegos de parque",
      "Juegos al aire libre",
      "Juegos infantiles",
      "Corporativo",
    ],
    includesOperator: false,
  },
  {
    slug: "plaza-blanda",
    name: "Plaza blanda",
    description: "Espacio seguro con juegos de encastre y didácticos para los más pequeños.",
    dimensions: "3m x 3m (Ajustable)",
    duration: "3 horas",
    price: "Consultar por WhatsApp",
    images: ["/juegos/plaza-blanda.jpg"],
    category: [
      "Juegos de parque",
      "Juegos de cumple",
      "Juegos para bebes",
      "Juegos infantiles",
      "Juegos al aire libre",
      "Juegos de interior"
    ],
    includesOperator: false,
  },
  {
    slug: "kiddies",
    name: "Kiddies",
    description: "Juegos mecánicos pequeños para farmacias o eventos infantiles.",
    dimensions: "1.2m x 0.8m",
    duration: "Jornada completa",
    price: "50.000",
    images: ["/juegos/kiddies.jpg"],
    category: [
      "Juegos infantiles",
    ],
    includesOperator: false,
  },
  {
    slug: "cancha-de-futbol-lona",
    name: "Cancha de futbol lona",
    description: "Superficie de lona de alta resistencia para jugar al fútbol.",
    dimensions: "10m x 5m",
    duration: "Jornada completa",
    price: "Consultar por WhatsApp",
    images: ["/juegos/futbol-lona.jpg"],
    category: [
      "Juegos de cumple",
      "Juegos al aire libre",
      "Juegos de adultos",
    ],
    includesOperator: false,
  },
  {
    slug: "arco-publicitario",
    name: "Arco publicitario",
    description: "Ideal para marcar ingresos o metas en maratones y eventos.",
    dimensions: "6m x 4m",
    duration: "Consultar",
    price: "Consultar por WhatsApp",
    images: ["/juegos/arco-publicitario.jpg"],
    category: [
      "Corporativo",
    ],
    includesOperator: false,
  },
  {
    slug: "mesa-minipool",
    name: "Mesa de Mini Pool",
    description: "Diversión clásica de salón en tamaño compacto.",
    dimensions: "1.8m x 1m",
    duration: "Jornada completa",
    price: "50.000",
    images: ["/juegos/minipool.jpg"],
    category: [
      "Juegos de estar",
      "Juegos de cumple",
      "Juegos de interior",
      "Juegos al aire libre",
      "Juegos infantiles",
      "Juegos de adultos",
    ],
    includesOperator: false,
  },
    {
    slug: "sapo",
    name: "Sapo",
    description: "Juego tradicional de puntería en madera barnizada.",
    dimensions: "0.5m x 0.5m",
    duration: "Jornada completa",
    price: "50.000",
    images: ["/juegos/sapo.jpg"],
    category: [
      "Juegos de estar",
      "Juegos de cumple",
      "Juegos de interior",
      "Juegos al aire libre",
      "Juegos infantiles",
      "Juegos de adultos",
    ],
    includesOperator: false,
  },
  {
    slug: "tejo",
    name: "Tejo",
    description: "Mesa de tejo de aire profesional.",
    dimensions: "1.6m x 0.8m",
    duration: "Jornada completa",
    price: "50.000",
    images: ["/juegos/tejo.jpg"],
    category: [
      "Juegos de estar",
      "Juegos de cumple",
      "Juegos de interior",
      "Juegos al aire libre",
      "Juegos infantiles",
      "Juegos de adultos",
    ],
    includesOperator: false,
  }, 
  */
];